print("SWAP TWO NOS WITHOUT TEMP VAR:")
a=input("Enter first number:")
b=input("Enter second number")
a=int(a)+int(b)
b=int(a)-int(b)
a=int(a)-int(b)
print("Value of a is",str(a))
print("Value of b is ",str(b))
